"use client"

import { create } from "zustand"
import { persist } from "zustand/middleware"

export type Language = "en" | "ar"

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.account": "Account",
    "nav.wishlist": "Wishlist",
    "nav.cart": "Cart",
    "nav.search": "Search",
    "nav.dashboard": "Dashboard",

    // Hero
    "hero.title": "STEP INTO",
    "hero.subtitle": "THE FUTURE",
    "hero.description": "Discover the latest drops from the world's most iconic sneaker brands. Limited editions, exclusive releases, and timeless classics.",
    "hero.shop": "Shop Now",
    "hero.explore": "Explore Collection",
    "hero.premium": "Premium Collection",
    "hero.desc": "Discover the finest selection of premium sneakers. Authentic, exclusive, and crafted for excellence.",
    "hero.learn-more": "Learn More",
    "stats.products": "Products",
    "stats.brands": "Brands",
    "stats.customers": "Customers",
    "stats.scroll": "SCROLL",
    "brand.exclusive": "Exclusive Drops",
    "brand.exclusive-desc": "First access to limited releases",
    "brand.authentic": "100% Authentic",
    "brand.authentic-desc": "Every pair verified genuine",
    "brand.shipping": "Free Shipping",
    "brand.shipping-desc": "On orders over $150",
    "featured.title": "FEATURED",
    "featured.subtitle": "Curated picks for the season",
    "new.badge": "JUST DROPPED",
    "new.title": "NEW ARRIVALS",
    "new.desc": "Fresh heat just landed. Be the first to cop the latest drops before they sell out.",
    "new.shop": "Shop New Drops",
    "new.drops.title": "NEW DROPS",
    "new.drops.subtitle": "Fresh releases you don't want to miss",
    "story.badge": "OUR STORY",
    "story.title": "WHERE PASSION MEETS PREMIUM QUALITY",
    "story.desc": "Born from a love of sneaker culture, SNKRVAULT brings you the most coveted kicks from around the world. Every pair is authenticated, every drop is curated.",
    "trending.title": "TRENDING NOW",
    "trending.subtitle": "What everyone's wearing",
    "newsletter.title": "STAY IN THE LOOP",
    "newsletter.desc": "Get early access to exclusive drops, special offers, and sneaker news.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.subscribe": "Subscribe",

    // Shop
    "shop.title": "Shop",
    "shop.all": "All",
    "shop.filters": "Filters",
    "shop.brand": "Brand",
    "shop.category": "Category",
    "shop.price": "Price Range",
    "shop.size": "Size",
    "shop.color": "Color",
    "shop.sort": "Sort By",
    "shop.sort.featured": "Featured",
    "shop.sort.newest": "Newest",
    "shop.sort.price-low": "Price: Low to High",
    "shop.sort.price-high": "Price: High to Low",
    "shop.products": "Products",
    "shop.clear": "Clear All",
    "shop.apply": "Apply Filters",
    "shop.no-products": "No products found",

    // Product
    "product.add-to-cart": "Add to Cart",
    "product.add-to-wishlist": "Add to Wishlist",
    "product.remove-from-wishlist": "Remove from Wishlist",
    "product.select-size": "Select Size",
    "product.description": "Description",
    "product.details": "Details",
    "product.shipping": "Shipping & Returns",
    "product.reviews": "Reviews",
    "product.related": "You May Also Like",
    "product.in-stock": "In Stock",
    "product.out-of-stock": "Out of Stock",
    "product.new": "New",
    "product.sale": "Sale",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.continue": "Continue Shopping",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.tax": "Tax",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.remove": "Remove",
    "cart.quantity": "Quantity",
    "cart.free-shipping": "Free Shipping",

    // Checkout
    "checkout.title": "Checkout",
    "checkout.shipping-info": "Shipping Information",
    "checkout.payment": "Payment Method",
    "checkout.review": "Review Order",
    "checkout.place-order": "Place Order",
    "checkout.first-name": "First Name",
    "checkout.last-name": "Last Name",
    "checkout.email": "Email",
    "checkout.phone": "Phone",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.state": "State",
    "checkout.zip": "ZIP Code",
    "checkout.country": "Country",
    "checkout.card-number": "Card Number",
    "checkout.expiry": "Expiry Date",
    "checkout.cvv": "CVV",
    "checkout.order-summary": "Order Summary",

    // Wishlist
    "wishlist.title": "Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.browse": "Browse Products",

    // Account
    "account.title": "My Account",
    "account.profile": "Profile",
    "account.orders": "Orders",
    "account.addresses": "Addresses",
    "account.settings": "Settings",
    "account.logout": "Logout",
    "account.login": "Login",
    "account.register": "Register",
    "account.welcome": "Welcome back",

    // About
    "about.title": "About Us",
    "about.story": "Our Story",
    "about.mission": "Our Mission",
    "about.team": "Our Team",

    // Contact
    "contact.title": "Contact Us",
    "contact.get-in-touch": "Get in Touch",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.hours": "Business Hours",

    // Footer
    "footer.newsletter": "Subscribe to Newsletter",
    "footer.newsletter-desc": "Get the latest updates on new releases and exclusive offers.",
    "footer.subscribe": "Subscribe",
    "footer.quick-links": "Quick Links",
    "footer.customer-service": "Customer Service",
    "footer.follow-us": "Follow Us",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.faq": "FAQ",
    "footer.returns": "Returns",
    "footer.track-order": "Track Order",
    "footer.shop-title": "Shop",
    "footer.help-title": "Help",
    "footer.stay-updated": "Stay Updated",
    "footer.new-arrivals": "New Arrivals",
    "footer.best-sellers": "Best Sellers",
    "footer.sale": "Sale",
    "footer.all-products": "All Products",
    "footer.contact-us": "Contact Us",
    "footer.faqs": "FAQs",
    "footer.shipping": "Shipping",
    "footer.about-us": "About Us",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.sustainability": "Sustainability",
    "footer.brand-desc": "Premium sneakers for those who demand excellence. Step into the future of footwear.",
    "footer.copyright": "© 2024 SNKRVAULT. All rights reserved.",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.overview": "Overview",
    "dashboard.products": "Products",
    "dashboard.orders": "Orders",
    "dashboard.customers": "Customers",
    "dashboard.analytics": "Analytics",
    "dashboard.settings": "Settings",
    "dashboard.total-revenue": "Total Revenue",
    "dashboard.total-orders": "Total Orders",
    "dashboard.total-customers": "Total Customers",
    "dashboard.total-products": "Total Products",
    "dashboard.recent-orders": "Recent Orders",
    "dashboard.top-products": "Top Products",
    "dashboard.revenue-chart": "Revenue Overview",
    "dashboard.add-product": "Add Product",
    "dashboard.edit-product": "Edit Product",
    "dashboard.delete-product": "Delete Product",
    "dashboard.search-products": "Search products...",
    "dashboard.search-orders": "Search orders...",
    "dashboard.search-customers": "Search customers...",
    "dashboard.status": "Status",
    "dashboard.date": "Date",
    "dashboard.customer": "Customer",
    "dashboard.amount": "Amount",
    "dashboard.action": "Action",
    "dashboard.pending": "Pending",
    "dashboard.processing": "Processing",
    "dashboard.shipped": "Shipped",
    "dashboard.delivered": "Delivered",
    "dashboard.cancelled": "Cancelled",
    "dashboard.view": "View",
    "dashboard.edit": "Edit",
    "dashboard.delete": "Delete",
    "dashboard.save": "Save",
    "dashboard.cancel": "Cancel",
    "dashboard.export": "Export",
    "dashboard.import": "Import",
    "dashboard.filter": "Filter",
    "dashboard.all-time": "All Time",
    "dashboard.today": "Today",
    "dashboard.this-week": "This Week",
    "dashboard.this-month": "This Month",
    "dashboard.this-year": "This Year",

    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.view-all": "View All",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.close": "Close",
  },
  ar: {
    // Header
    "nav.home": "الرئيسية",
    "nav.shop": "المتجر",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.account": "حسابي",
    "nav.wishlist": "المفضلة",
    "nav.cart": "السلة",
    "nav.search": "بحث",
    "nav.dashboard": "لوحة التحكم",

    // Hero
    "hero.title": "اخطو نحو",
    "hero.subtitle": "المستقبل",
    "hero.description": "اكتشف أحدث الإصدارات من أشهر ماركات الأحذية الرياضية في العالم. إصدارات محدودة، إطلاقات حصرية، وكلاسيكيات خالدة.",
    "hero.shop": "تسوق الآن",
    "hero.explore": "استكشف المجموعة",
    "hero.premium": "المجموعة المميزة",
    "hero.desc": "اكتشف أفضل تشكيلة من الأحذية الرياضية الفاخرة. أصلية، حصرية، ومصنوعة بإتقان.",
    "hero.learn-more": "اعرف المزيد",
    "stats.products": "المنتجات",
    "stats.brands": "الماركات",
    "stats.customers": "العملاء",
    "stats.scroll": "لأسفل",
    "brand.exclusive": "إصدارات حصرية",
    "brand.exclusive-desc": "أول وصول للإصدارات المحدودة",
    "brand.authentic": "أصلية 100%",
    "brand.authentic-desc": "كل زوج تم التحقق من أصالته",
    "brand.shipping": "شحن مجاني",
    "brand.shipping-desc": "للطلبات فوق 150 دولار",
    "featured.title": "المميزة",
    "featured.subtitle": "اختياراتنا لهذا الموسم",
    "new.badge": "وصل حديثاً",
    "new.title": "أحدث الإصدارات",
    "new.desc": "أحدث الموديلات وصلت للتو. كن أول من يمتلكها قبل نفاد الكمية.",
    "new.shop": "تسوق أحدث الإصدارات",
    "new.drops.title": "إصدارات جديدة",
    "new.drops.subtitle": "إصدارات جديدة لا تفوتك",
    "story.badge": "قصتنا",
    "story.title": "حيث يلتقي الشغف بالمنتجات الفاخرة",
    "story.desc": "وُلدت SNKRVAULT من حب ثقافة الأحذية الرياضية، لتقدم لك أكثر الأحذية طلباً في العالم. كل زوج أصلي، وكل إصدار مختار بعناية.",
    "trending.title": "الأكثر رواجاً",
    "trending.subtitle": "ما يرتديه الجميع الآن",
    "newsletter.title": "ابق على اطلاع",
    "newsletter.desc": "احصل على وصول مبكر للإصدارات الحصرية، عروض خاصة، وأخبار الأحذية الرياضية.",
    "newsletter.placeholder": "أدخل بريدك الإلكتروني",
    "newsletter.subscribe": "اشترك",

    // Shop
    "shop.title": "المتجر",
    "shop.all": "الكل",
    "shop.filters": "التصفية",
    "shop.brand": "العلامة التجارية",
    "shop.category": "الفئة",
    "shop.price": "نطاق السعر",
    "shop.size": "المقاس",
    "shop.color": "اللون",
    "shop.sort": "ترتيب حسب",
    "shop.sort.featured": "المميز",
    "shop.sort.newest": "الأحدث",
    "shop.sort.price-low": "السعر: من الأقل للأعلى",
    "shop.sort.price-high": "السعر: من الأعلى للأقل",
    "shop.products": "منتجات",
    "shop.clear": "مسح الكل",
    "shop.apply": "تطبيق الفلاتر",
    "shop.no-products": "لا توجد منتجات",

    // Product
    "product.add-to-cart": "أضف للسلة",
    "product.add-to-wishlist": "أضف للمفضلة",
    "product.remove-from-wishlist": "إزالة من المفضلة",
    "product.select-size": "اختر المقاس",
    "product.description": "الوصف",
    "product.details": "التفاصيل",
    "product.shipping": "الشحن والإرجاع",
    "product.reviews": "التقييمات",
    "product.related": "قد يعجبك أيضاً",
    "product.in-stock": "متوفر",
    "product.out-of-stock": "غير متوفر",
    "product.new": "جديد",
    "product.sale": "تخفيض",

    // Cart
    "cart.title": "سلة التسوق",
    "cart.empty": "سلة التسوق فارغة",
    "cart.continue": "متابعة التسوق",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن",
    "cart.tax": "الضريبة",
    "cart.total": "الإجمالي",
    "cart.checkout": "إتمام الشراء",
    "cart.remove": "إزالة",
    "cart.quantity": "الكمية",
    "cart.free-shipping": "شحن مجاني",

    // Checkout
    "checkout.title": "إتمام الشراء",
    "checkout.shipping-info": "معلومات الشحن",
    "checkout.payment": "طريقة الدفع",
    "checkout.review": "مراجعة الطلب",
    "checkout.place-order": "تأكيد الطلب",
    "checkout.first-name": "الاسم الأول",
    "checkout.last-name": "اسم العائلة",
    "checkout.email": "البريد الإلكتروني",
    "checkout.phone": "الهاتف",
    "checkout.address": "العنوان",
    "checkout.city": "المدينة",
    "checkout.state": "المنطقة",
    "checkout.zip": "الرمز البريدي",
    "checkout.country": "الدولة",
    "checkout.card-number": "رقم البطاقة",
    "checkout.expiry": "تاريخ الانتهاء",
    "checkout.cvv": "رمز الأمان",
    "checkout.order-summary": "ملخص الطلب",

    // Wishlist
    "wishlist.title": "المفضلة",
    "wishlist.empty": "قائمة المفضلة فارغة",
    "wishlist.browse": "تصفح المنتجات",

    // Account
    "account.title": "حسابي",
    "account.profile": "الملف الشخصي",
    "account.orders": "الطلبات",
    "account.addresses": "العناوين",
    "account.settings": "الإعدادات",
    "account.logout": "تسجيل الخروج",
    "account.login": "تسجيل الدخول",
    "account.register": "إنشاء حساب",
    "account.welcome": "مرحباً بعودتك",

    // About
    "about.title": "من نحن",
    "about.story": "قصتنا",
    "about.mission": "مهمتنا",
    "about.team": "فريقنا",

    // Contact
    "contact.title": "اتصل بنا",
    "contact.get-in-touch": "تواصل معنا",
    "contact.name": "الاسم",
    "contact.email": "البريد الإلكتروني",
    "contact.message": "الرسالة",
    "contact.send": "إرسال الرسالة",
    "contact.address": "العنوان",
    "contact.phone": "الهاتف",
    "contact.hours": "ساعات العمل",

    // Footer
    "footer.newsletter": "اشترك في النشرة الإخبارية",
    "footer.newsletter-desc": "احصل على آخر التحديثات حول الإصدارات الجديدة والعروض الحصرية.",
    "footer.subscribe": "اشترك",
    "footer.quick-links": "روابط سريعة",
    "footer.customer-service": "خدمة العملاء",
    "footer.follow-us": "تابعنا",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.faq": "الأسئلة الشائعة",
    "footer.returns": "الإرجاع",
    "footer.track-order": "تتبع الطلب",
    "footer.shop-title": "تسوق",
    "footer.help-title": "المساعدة",
    "footer.stay-updated": "ابق على اطلاع",
    "footer.new-arrivals": "أحدث الإصدارات",
    "footer.best-sellers": "الأكثر مبيعاً",
    "footer.sale": "التخفيضات",
    "footer.all-products": "كل المنتجات",
    "footer.contact-us": "اتصل بنا",
    "footer.faqs": "الأسئلة الشائعة",
    "footer.shipping": "الشحن",
    "footer.about-us": "من نحن",
    "footer.careers": "الوظائف",
    "footer.press": "الصحافة",
    "footer.sustainability": "الاستدامة",
    "footer.brand-desc": "أحذية رياضية فاخرة لمن يبحث عن التميز. اخطو نحو مستقبل الأحذية.",
    "footer.copyright": "© 2024 SNKRVAULT. جميع الحقوق محفوظة.",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.overview": "نظرة عامة",
    "dashboard.products": "المنتجات",
    "dashboard.orders": "الطلبات",
    "dashboard.customers": "العملاء",
    "dashboard.analytics": "التحليلات",
    "dashboard.settings": "الإعدادات",
    "dashboard.total-revenue": "إجمالي الإيرادات",
    "dashboard.total-orders": "إجمالي الطلبات",
    "dashboard.total-customers": "إجمالي العملاء",
    "dashboard.total-products": "إجمالي المنتجات",
    "dashboard.recent-orders": "الطلبات الأخيرة",
    "dashboard.top-products": "أفضل المنتجات",
    "dashboard.revenue-chart": "نظرة عامة على الإيرادات",
    "dashboard.add-product": "إضافة منتج",
    "dashboard.edit-product": "تعديل المنتج",
    "dashboard.delete-product": "حذف المنتج",
    "dashboard.search-products": "البحث في المنتجات...",
    "dashboard.search-orders": "البحث في الطلبات...",
    "dashboard.search-customers": "البحث في العملاء...",
    "dashboard.status": "الحالة",
    "dashboard.date": "التاريخ",
    "dashboard.customer": "العميل",
    "dashboard.amount": "المبلغ",
    "dashboard.action": "الإجراء",
    "dashboard.pending": "قيد الانتظار",
    "dashboard.processing": "قيد المعالجة",
    "dashboard.shipped": "تم الشحن",
    "dashboard.delivered": "تم التسليم",
    "dashboard.cancelled": "ملغي",
    "dashboard.view": "عرض",
    "dashboard.edit": "تعديل",
    "dashboard.delete": "حذف",
    "dashboard.save": "حفظ",
    "dashboard.cancel": "إلغاء",
    "dashboard.export": "تصدير",
    "dashboard.import": "استيراد",
    "dashboard.filter": "تصفية",
    "dashboard.all-time": "كل الوقت",
    "dashboard.today": "اليوم",
    "dashboard.this-week": "هذا الأسبوع",
    "dashboard.this-month": "هذا الشهر",
    "dashboard.this-year": "هذه السنة",

    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.success": "تم بنجاح",
    "common.confirm": "تأكيد",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.add": "إضافة",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.view-all": "عرض الكل",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.close": "إغلاق",
  },
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "en",
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const { language } = get()
        return translations[language][key] || key
      },
    }),
    {
      name: "language-storage",
    }
  )
)
