"use client"

import { create } from "zustand"
import { persist, createJSONStorage } from "zustand/middleware"

export type Language = "en" | "ar"

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.account": "Account",
    "nav.wishlist": "Wishlist",
    "nav.cart": "Cart",
    "nav.search": "Search",
    "nav.dashboard": "Dashboard",

    // Hero
    "hero.title": "STEP INTO",
    "hero.subtitle": "THE FUTURE",
    "hero.description": "Discover the latest drops from the world's most iconic sneaker brands. Limited editions, exclusive releases, and timeless classics.",
    "hero.shop": "Shop Now",
    "hero.explore": "Explore Collection",
    "hero.premium": "Premium Collection",
    "hero.desc": "Discover the finest selection of premium sneakers. Authentic, exclusive, and crafted for excellence.",
    "hero.learn-more": "Learn More",
    "stats.products": "Products",
    "stats.brands": "Brands",
    "stats.customers": "Customers",
    "stats.scroll": "SCROLL",
    "brand.exclusive": "Exclusive Drops",
    "brand.exclusive-desc": "First access to limited releases",
    "brand.authentic": "100% Authentic",
    "brand.authentic-desc": "Every pair verified genuine",
    "brand.shipping": "Free Shipping",
    "brand.shipping-desc": "On orders over $150",
    "featured.title": "FEATURED",
    "featured.subtitle": "Curated picks for the season",
    "featured.view-all": "View All",
    "new.badge": "JUST DROPPED",
    "new.title": "NEW ARRIVALS",
    "new.desc": "Fresh heat just landed. Be the first to cop the latest drops before they sell out.",
    "new.shop": "Shop New Drops",
    "new.drops.title": "NEW DROPS",
    "new.drops.subtitle": "Fresh releases you don't want to miss",
    "story.badge": "OUR STORY",
    "story.title": "WHERE PASSION MEETS PREMIUM QUALITY",
    "story.desc": "Born from a love of sneaker culture, SNKRVAULT brings you the most coveted kicks from around the world. Every pair is authenticated, every drop is curated.",
    "trending.title": "TRENDING NOW",
    "trending.subtitle": "What everyone's wearing",
    "newsletter.title": "STAY IN THE LOOP",
    "newsletter.desc": "Get early access to exclusive drops, special offers, and sneaker news.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.subscribe": "Subscribe",

    // Shop
    "shop.title": "Shop",
    "shop.all": "All",
    "shop.filters": "Filters",
    "shop.brand": "Brand",
    "shop.category": "Category",
    "shop.price": "Price Range",
    "shop.size": "Size",
    "shop.color": "Color",
    "shop.sort": "Sort By",
    "shop.sort.featured": "Featured",
    "shop.sort.newest": "Newest",
    "shop.sort.popular": "Popular",
    "shop.sort.rating": "Rating",
    "shop.sort.price-low": "Price: Low to High",
    "shop.sort.price-high": "Price: High to Low",
    "shop.products": "Products",
    "shop.products-count": "products",
    "shop.clear": "Clear All",
    "shop.clear-all": "Clear All",
    "shop.apply": "Apply Filters",
    "shop.to": "to",
    "shop.gender": "Gender",
    "shop.no-products": "No products found",

    // Product
    "product.add-to-cart": "Add to Cart",
    "product.add-to-wishlist": "Add to Wishlist",
    "product.remove-from-wishlist": "Remove from Wishlist",
    "product.select-size": "Select Size",
    "product.description": "Description",
    "product.details": "Details",
    "product.shipping": "Shipping & Returns",
    "product.reviews": "Reviews",
    "product.related": "You May Also Like",
    "product.in-stock": "In Stock",
    "product.out-of-stock": "Out of Stock",
    "product.new": "New",
    "product.sale": "Sale",
    "product.limited": "Limited",
    "product.off": "OFF",
    "product.reviews-count": "reviews",
    "product.size-guide": "Size Guide",
    "product.buy-now": "Buy Now",
    "product.select-size-error": "Please select a size",
    "product.added-to-cart": "Added to cart",
    "product.size": "Size",
    "product.free-shipping": "Free Shipping on orders over 500 EGP",
    "product.returns": "14-Day Returns",
    "product.authentic": "100% Authentic Products",
    "product.shipping-desc-1": "Free standard shipping on orders over $150.",
    "product.shipping-desc-2": "Express shipping available for $12.99.",
    "product.shipping-desc-3": "Free returns within 30 days of purchase.",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty-desc": "Looks like you haven't added any sneakers to your cart yet.",
    "cart.start-shopping": "Start Shopping",
    "cart.continue-shopping": "Continue Shopping",
    "cart.clear-all": "Clear All",
    "cart.view-cart": "View Cart",
    "cart.sidebar-title": "Your Cart",
    "cart.shipping-note": "Shipping and taxes calculated at checkout",
    "cart.continue": "Continue Shopping",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.tax": "Tax",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.remove": "Remove",
    "cart.quantity": "Quantity",
    "cart.free-shipping": "Free Shipping",
    "cart.summary": "Order Summary",
    "cart.promo-code": "Promo Code",
    "cart.enter-code": "Enter code",
    "cart.apply": "Apply",
    "cart.promo-applied": "Promo code applied!",
    "cart.discount": "Discount",
    "cart.free": "Free",
    "cart.free-shipping-msg": "Add $150 more for free shipping",
    "cart.suggested": "CUSTOMERS ALSO BOUGHT",

    // Checkout
    "checkout.title": "Checkout",
    "checkout.shipping": "Shipping",
    "checkout.shipping-info": "Shipping Information",
    "checkout.payment": "Payment Method",
    "checkout.review": "Review Order",
    "checkout.place-order": "Place Order",
    "checkout.first-name": "First Name",
    "checkout.last-name": "Last Name",
    "checkout.email": "Email",
    "checkout.phone": "Phone",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.state": "State",
    "checkout.zip": "ZIP Code",
    "checkout.country": "Country",
    "checkout.card-number": "Card Number",
    "checkout.expiry": "Expiry Date",
    "checkout.cvv": "CVV",
    "checkout.order-summary": "Order Summary",
    "checkout.contact-shipping": "Contact & Shipping",
    "checkout.shipping-method": "Shipping Method",
    "checkout.payment-info": "Payment Information",
    "checkout.review-order": "Review Your Order",
    "checkout.shipping-address": "Shipping Address",
    "checkout.payment-method": "Payment Method",
    "checkout.order-items": "Order Items",
    "checkout.save-info": "Save this information for next time",
    "checkout.standard": "Standard Shipping",
    "checkout.express": "Express Shipping",
    "checkout.overnight": "Overnight Shipping",
    "checkout.business-days": "business days",
    "checkout.next-day": "Next business day",
    "checkout.card": "Credit / Debit Card",
    "checkout.card-name": "Name on Card",
    "checkout.secure": "Your payment information is secure and encrypted",
    "checkout.ordered": "Order Confirmed!",
    "checkout.thank-you": "Thank you for your purchase. Your order number is:",
    "checkout.confirmation": "We'll send you a confirmation email with tracking details shortly.",
    "checkout.back-cart": "Back to Cart",
    "checkout.delivery": "Delivery",
    "checkout.empty-cart": "Your cart is empty",
    "checkout.continue-shopping": "Continue Shopping",

    // About
    "about.story": "OUR STORY",
    "about.title": "BORN FROM PASSION",
    "about.description": "SNKRVAULT was founded with a simple mission: to bring the world's most coveted sneakers to collectors and enthusiasts everywhere. We believe every pair tells a story.",
    "about.stats.customers": "Happy Customers",
    "about.stats.partners": "Brand Partners",
    "about.stats.sold": "Sneakers Sold",
    "about.stats.authenticity": "Authenticity Rate",
    "about.values.title": "OUR VALUES",
    "about.values.description": "What drives us every day to deliver the best sneaker experience.",
    "about.values.authentic.title": "100% Authentic",
    "about.values.authentic.description": "Every sneaker is verified by our team of experts before it reaches you.",
    "about.values.global.title": "Global Reach",
    "about.values.global.description": "We ship to over 100 countries, bringing the best kicks worldwide.",
    "about.values.community.title": "Community First",
    "about.values.community.description": "Built by sneakerheads, for sneakerheads. We get it.",
    "about.values.sustainable.title": "Sustainable",
    "about.values.sustainable.description": "Eco-friendly packaging and carbon-neutral shipping options.",
    "about.journey": "OUR JOURNEY",
    "about.timeline.2019.title": "The Beginning",
    "about.timeline.2019.description": "Started as a passion project by two sneaker enthusiasts.",
    "about.timeline.2020.title": "Going Digital",
    "about.timeline.2020.description": "Launched our online platform during the pandemic.",
    "about.timeline.2021.title": "Rapid Growth",
    "about.timeline.2021.description": "Expanded to 50+ countries and 100K customers.",
    "about.timeline.2022.title": "Authentication Lab",
    "about.timeline.2022.description": "Opened our state-of-the-art authentication facility.",
    "about.timeline.2023.title": "Global Presence",
    "about.timeline.2023.description": "Became a trusted name in the sneaker community worldwide.",
    "about.timeline.2024.title": "The Future",
    "about.timeline.2024.description": "Continuing to innovate and serve sneaker culture.",
    "about.cta.title": "JOIN THE VAULT",
    "about.cta.description": "Be part of a community that shares your passion for sneakers.",
    "about.cta.button": "Shop Now",

    // Contact
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.info.address": "Address",
    "contact.title": "CONTACT US",
    "contact.description": "Have a question or need help? We're here for you.",
    "contact.form-title": "Send us a message",
    "contact.name": "Name",
    "contact.name-placeholder": "Your name",
    "contact.email": "Email",
    "contact.email-placeholder": "your@email.com",
    "contact.subject": "Subject",
    "contact.select-topic": "Select a topic",
    "contact.topic.order": "Order Inquiry",
    "contact.topic.product": "Product Question",
    "contact.topic.return": "Returns & Exchanges",
    "contact.topic.other": "Other",
    "contact.message": "Message",
    "contact.message-placeholder": "How can we help you?",
    "contact.send": "Send Message",
    "contact.get-in-touch": "Get in touch",
    "contact.map-coming": "Interactive map coming soon",
    "contact.live-chat": "Start Live Chat",
    "contact.message-sent": "Message sent!",
    "contact.message-sent-desc": "We'll get back to you within 24 hours.",
    "contact.faq.track.question": "How do I track my order?",
    "contact.faq.track.answer": "Once your order ships, you'll receive an email with a tracking number. You can also track your order in your account under \"Orders\".",
    "contact.faq.return.question": "What is your return policy?",
    "contact.faq.return.answer": "We offer free returns within 30 days of purchase for unworn items in original packaging. Contact us to initiate a return.",
    "contact.faq.authentic.question": "Are all sneakers authentic?",
    "contact.faq.authentic.answer": "Yes! Every sneaker goes through our rigorous authentication process. We guarantee 100% authenticity or your money back.",
    "contact.faq.shipping.question": "How long does shipping take?",
    "contact.faq.shipping.answer": "Standard shipping takes 5-7 business days. Express (2-3 days) and overnight options are available at checkout.",
    "contact.faq.international.question": "Do you ship internationally?",
    "contact.faq.international.answer": "Yes! We ship to over 100 countries. International shipping typically takes 7-14 business days.",
    "contact.faq.size.question": "How do I know my size?",
    "contact.faq.size.answer": "Check our size guide on each product page. If you're between sizes, we recommend going up for a more comfortable fit.",
    "contact.faq.title": "FREQUENTLY ASKED QUESTIONS",

    // Wishlist
    "wishlist.title": "Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.empty-desc": "Save items you love by clicking the heart icon on any product.",
    "wishlist.browse": "Browse Products",
    "wishlist.share": "Share",
    "wishlist.items-saved": "items saved",
    "wishlist.move-to-cart": "Move to Cart",
    "wishlist.moved-to-cart": "Moved to cart",
    "wishlist.moved-desc": "added to your cart",
    "wishlist.link-copied": "Link copied",
    "wishlist.link-copied-desc": "Wishlist link copied to clipboard",
    "wishlist.copy-failed": "Failed to copy link",
    "wishlist.start-shopping": "Start Shopping",

    // Search
    "search.title": "Search",
    "search.placeholder": "Search for sneakers...",
    "search.no-results": "No results found for",
    "search.popular": "Popular Searches",

    // Account
    "account.title": "My Account",
    "account.profile": "Profile",
    "account.orders": "Orders",
    "account.addresses": "Addresses",
    "account.settings": "Settings",
    "account.logout": "Logout",
    "account.login": "Login",
    "account.register": "Register",
    "account.welcome": "Welcome back",
    "account.profile-info": "Profile Information",
    "account.first-name": "First Name",
    "account.last-name": "Last Name",
    "account.save-changes": "Save Changes",
    "account.change-password": "Change Password",
    "account.current-password": "Current Password",
    "account.new-password": "New Password",
    "account.confirm-password": "Confirm New Password",
    "account.update-password": "Update Password",
    "account.order-history": "Order History",
    "account.items": "item(s)",
    "account.saved-addresses": "Saved Addresses",
    "account.add-address": "Add New Address",
    "account.default": "Default",
    "account.edit": "Edit",
    "account.wishlist-desc": "View and manage your saved items.",
    "account.go-wishlist": "Go to Wishlist",
    "account.preferences": "Preferences",
    "account.email-notifications": "Email Notifications",
    "account.email-notifications-desc": "Receive updates about orders and promotions",
    "account.sms-notifications": "SMS Notifications",
    "account.sms-notifications-desc": "Get text updates for shipping and delivery",
    "account.newsletter-pref": "Newsletter",
    "account.newsletter-pref-desc": "Weekly updates on new drops and exclusive offers",
    "account.preferred-size": "Preferred Size",
    "account.save-preferences": "Save Preferences",
    "account.work": "Work",

    // Footer
    "footer.newsletter": "Subscribe to Newsletter",
    "footer.newsletter-desc": "Get the latest updates on new releases and exclusive offers.",
    "footer.subscribe": "Subscribe",
    "footer.quick-links": "Quick Links",
    "footer.customer-service": "Customer Service",
    "footer.follow-us": "Follow Us",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.faq": "FAQ",
    "footer.returns": "Returns",
    "footer.shop-title": "Shop",
    "footer.help-title": "Help",
    "footer.company-title": "Company",
    "footer.new-arrivals": "New Arrivals",
    "footer.best-sellers": "Best Sellers",
    "footer.sale": "Sale",
    "footer.all-products": "All Products",
    "footer.contact-us": "Contact Us",
    "footer.faqs": "FAQs",
    "footer.shipping": "Shipping",
    "footer.about-us": "About Us",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.sustainability": "Sustainability",
    "footer.brand-desc": "Your destination for authentic sneakers. We bring you the latest drops and timeless classics from the world's most coveted brands.",
    "footer.copyright": "© 2024 SNKRVAULT. All rights reserved.",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.overview": "Overview",
    "dashboard.products": "Products",
    "dashboard.orders": "Orders",
    "dashboard.customers": "Customers",
    "dashboard.analytics": "Analytics",
    "dashboard.settings": "Settings",
    "dashboard.total-revenue": "Total Revenue",
    "dashboard.total-orders": "Total Orders",
    "dashboard.total-customers": "Total Customers",
    "dashboard.total-products": "Total Products",
    "dashboard.recent-orders": "Recent Orders",
    "dashboard.top-products": "Top Products",
    "dashboard.revenue-chart": "Weekly Revenue",
    "dashboard.orders-status": "Orders by Status",
    "dashboard.sales-by-category": "Sales by Category",
    "dashboard.add-product": "Add Product",
    "dashboard.edit-product": "Edit Product",
    "dashboard.delete-product": "Delete Product",
    "dashboard.search-products": "Search products...",
    "dashboard.search-orders": "Search orders...",
    "dashboard.search-customers": "Search customers...",
    "dashboard.status": "Status",
    "dashboard.date": "Date",
    "dashboard.customer": "Customer",
    "dashboard.amount": "Amount",
    "dashboard.action": "Action",
    "dashboard.pending": "Pending",
    "dashboard.processing": "Processing",
    "dashboard.shipped": "Shipped",
    "dashboard.delivered": "Delivered",
    "dashboard.cancelled": "Cancelled",
    "dashboard.view": "View",
    "dashboard.edit": "Edit",
    "dashboard.delete": "Delete",
    "dashboard.save": "Save",
    "dashboard.cancel": "Cancel",
    "dashboard.export": "Export",
    "dashboard.import": "Import",
    "dashboard.filter": "Filter",
    "dashboard.all-time": "All Time",
    "dashboard.today": "Today",
    "dashboard.this-week": "This Week",
    "dashboard.this-month": "This Month",
    "dashboard.this-year": "This Year",
    "dashboard.from-last-month": "from last month",
    "dashboard.sold": "sold",

    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.view-all": "View All",
    "common.back": "Back",
    "common.continue": "Continue",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.close": "Close",
  },
  ar: {
    // Header
    "nav.home": "الرئيسية",
    "nav.shop": "المتجر",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.account": "حسابي",
    "nav.wishlist": "المفضلة",
    "nav.cart": "السلة",
    "nav.search": "بحث",
    "nav.dashboard": "لوحة التحكم",

    // Hero
    "hero.title": "اخطو نحو",
    "hero.subtitle": "المستقبل",
    "hero.description": "اكتشف أحدث الإصدارات من أشهر ماركات الأحذية الرياضية في العالم. إصدارات محدودة، إطلاقات حصرية، وكلاسيكيات خالدة.",
    "hero.shop": "تسوق الآن",
    "hero.explore": "استكشف المجموعة",
    "hero.premium": "المجموعة المميزة",
    "hero.desc": "اكتشف أفضل تشكيلة من الأحذية الرياضية الفاخرة. أصلية، حصرية، ومصنوعة بإتقان.",
    "hero.learn-more": "اعرف المزيد",
    "stats.products": "المنتجات",
    "stats.brands": "الماركات",
    "stats.customers": "العملاء",
    "stats.scroll": "لأسفل",
    "brand.exclusive": "إصدارات حصرية",
    "brand.exclusive-desc": "أول وصول للإصدارات المحدودة",
    "brand.authentic": "أصلية 100%",
    "brand.authentic-desc": "كل زوج تم التحقق من أصالته",
    "brand.shipping": "شحن مجاني",
    "brand.shipping-desc": "للطلبات فوق 150 دولار",
    "featured.title": "المميزة",
    "featured.subtitle": "اختياراتنا لهذا الموسم",
    "featured.view-all": "عرض الكل",
    "new.badge": "وصل حديثاً",
    "new.title": "أحدث الإصدارات",
    "new.desc": "أحدث الموديلات وصلت للتو. كن أول من يمتلكها قبل نفاد الكمية.",
    "new.shop": "تسوق أحدث الإصدارات",
    "new.drops.title": "إصدارات جديدة",
    "new.drops.subtitle": "إصدارات جديدة لا تفوتك",
    "story.badge": "قصتنا",
    "story.title": "حيث يلتقي الشغف بالمنتجات الفاخرة",
    "story.desc": "وُلدت SNKRVAULT من حب ثقافة الأحذية الرياضية، لتقدم لك أكثر الأحذية طلباً في العالم. كل زوج أصلي، وكل إصدار مختار بعناية.",
    "trending.title": "الأكثر رواجاً",
    "trending.subtitle": "ما يرتديه الجميع الآن",
    "newsletter.title": "ابق على اطلاع",
    "newsletter.desc": "احصل على وصول مبكر للإصدارات الحصرية، عروض خاصة، وأخبار الأحذية الرياضية.",
    "newsletter.placeholder": "أدخل بريدك الإلكتروني",
    "newsletter.subscribe": "اشترك",

    // Shop
    "shop.title": "المتجر",
    "shop.all": "الكل",
    "shop.filters": "التصفية",
    "shop.brand": "العلامة التجارية",
    "shop.category": "الفئة",
    "shop.price": "نطاق السعر",
    "shop.size": "المقاس",
    "shop.color": "اللون",
    "shop.sort": "ترتيب حسب",
    "shop.sort.featured": "المميز",
    "shop.sort.newest": "الأحدث",
    "shop.sort.popular": "الأكثر شعبية",
    "shop.sort.rating": "التقييم",
    "shop.sort.price-low": "السعر: من الأقل للأعلى",
    "shop.sort.price-high": "السعر: من الأعلى للأقل",
    "shop.products": "منتجات",
    "shop.products-count": "منتج",
    "shop.clear": "مسح الكل",
    "shop.clear-all": "مسح الكل",
    "shop.to": "إلى",
    "shop.gender": "الجنس",
    "shop.apply": "تطبيق الفلاتر",
    "shop.no-products": "لا توجد منتجات",

    // Product
    "product.add-to-cart": "أضف للسلة",
    "product.add-to-wishlist": "أضف للمفضلة",
    "product.remove-from-wishlist": "إزالة من المفضلة",
    "product.select-size": "اختر المقاس",
    "product.description": "الوصف",
    "product.details": "التفاصيل",
    "product.shipping": "الشحن والإرجاع",
    "product.reviews": "التقييمات",
    "product.related": "قد يعجبك أيضاً",
    "product.in-stock": "متوفر",
    "product.out-of-stock": "غير متوفر",
    "product.limited": "محدود",
    "product.off": "خصم",
    "product.reviews-count": "تقييم",
    "product.new": "جديد",
    "product.sale": "تخفيض",
    "product.size-guide": "دليل المقاسات",
    "product.buy-now": "اشتري الآن",
    "product.select-size-error": "الرجاء اختيار مقاس",
    "product.added-to-cart": "تمت الإضافة للسلة",
    "product.size": "المقاس",
    "product.free-shipping": "شحن مجاني للطلبات فوق 500 ج.م",
    "product.returns": "إرجاع خلال 14 يوم",
    "product.authentic": "منتجات أصلية 100%",
    "product.shipping-desc-1": "شحن مجاني قياسي للطلبات فوق 150 دولار.",
    "product.shipping-desc-2": "الشحن السريع متاح مقابل 12.99 دولار.",
    "product.shipping-desc-3": "إرجاع مجاني خلال 30 يوماً من الشراء.",

    // Cart
    "cart.title": "سلة التسوق",
    "cart.empty": "سلة التسوق فارغة",
    "cart.empty-desc": "يبدو أنك لم تضف أي أحذية رياضية إلى سلة التسوق بعد.",
    "cart.start-shopping": "ابدأ التسوق",
    "cart.continue": "متابعة التسوق",
    "cart.continue-shopping": "متابعة التسوق",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن",
    "cart.tax": "الضريبة",
    "cart.total": "الإجمالي",
    "cart.checkout": "إتمام الشراء",
    "cart.remove": "إزالة",
    "cart.quantity": "الكمية",
    "cart.free-shipping": "شحن مجاني",
    "cart.summary": "ملخص الطلب",
    "cart.promo-code": "رمز الترويج",
    "cart.enter-code": "أدخل الرمز",
    "cart.apply": "تطبيق",
    "cart.promo-applied": "تم تطبيق الرمز الترويجي!",
    "cart.discount": "الخصم",
    "cart.free": "مجاني",
    "cart.free-shipping-msg": "أضف 150 دولار أكثر للحصول على شحن مجاني",
    "cart.suggested": "عملاء آخرون اشتروا أيضاً",
    "cart.clear-all": "مسح الكل",
    "cart.view-cart": "عرض السلة",
    "cart.sidebar-title": "سلتك",
    "cart.shipping-note": "يتم حساب الشحن والضرائب عند الدفع",

    // Checkout
    "checkout.title": "إتمام الشراء",
    "checkout.shipping": "الشحن",
    "checkout.shipping-info": "معلومات الشحن",
    "checkout.payment": "طريقة الدفع",
    "checkout.review": "مراجعة الطلب",
    "checkout.place-order": "تأكيد الطلب",
    "checkout.first-name": "الاسم الأول",
    "checkout.last-name": "اسم العائلة",
    "checkout.email": "البريد الإلكتروني",
    "checkout.phone": "الهاتف",
    "checkout.address": "العنوان",
    "checkout.city": "المدينة",
    "checkout.state": "المنطقة",
    "checkout.zip": "الرمز البريدي",
    "checkout.country": "الدولة",
    "checkout.card-number": "رقم البطاقة",
    "checkout.expiry": "تاريخ الانتهاء",
    "checkout.cvv": "رمز الأمان",
    "checkout.order-summary": "ملخص الطلب",
    "checkout.contact-shipping": "التواصل والشحن",
    "checkout.shipping-method": "طريقة الشحن",
    "checkout.payment-info": "معلومات الدفع",
    "checkout.review-order": "مراجعة الطلب",
    "checkout.shipping-address": "عنوان الشحن",
    "checkout.payment-method": "طريقة الدفع",
    "checkout.order-items": "عناصر الطلب",
    "checkout.save-info": "حفظ هذه المعلومات للمرة القادمة",
    "checkout.standard": "الشحن القياسي",
    "checkout.express": "الشحن السريع",
    "checkout.overnight": "الشحن الليلي",
    "checkout.business-days": "أيام عمل",
    "checkout.next-day": "يوم العمل التالي",
    "checkout.card": "بطاقة ائتمان/خصم",
    "checkout.card-name": "الاسم على البطاقة",
    "checkout.secure": "معلومات الدفع الخاصة بك آمنة ومشفرة",
    "checkout.ordered": "تم تأكيد الطلب!",
    "checkout.thank-you": "شكراً لشرائك. رقم طلبك هو:",
    "checkout.confirmation": "سنرسل لك رسالة تأكيد بالبريد الإلكتروني مع تفاصيل التتبع قريباً.",
    "checkout.back-cart": "العودة للسلة",
    "checkout.delivery": "التوصيل",
    "checkout.empty-cart": "سلة التسوق فارغة",
    "checkout.continue-shopping": "متابعة التسوق",

    // About
    "about.story": "قصتنا",
    "about.title": "مولود من الشغف",
    "about.description": "تأسس SNKRVAULT بمهمة بسيطة: جلب الأحذية الأكثر طلباً في العالم إلى جامعي ومحبي الأحذية في كل مكان. نؤمن أن كل زوج يحكي قصة.",
    "about.stats.customers": "عملاء سعداء",
    "about.stats.partners": "شركاء العلامات التجارية",
    "about.stats.sold": "أحذية تم بيعها",
    "about.stats.authenticity": "معدل الأصالة",
    "about.values.title": "قيمنا",
    "about.values.description": "ما يدفعنا كل يوم لتقديم أفضل تجربة للأحذية.",
    "about.values.authentic.title": "أصلي 100%",
    "about.values.authentic.description": "يتم التحقق من كل حذاء من قبل فريقنا من الخبراء قبل وصوله إليك.",
    "about.values.global.title": "وصول عالمي",
    "about.values.global.description": "نحن نشحن إلى أكثر من 100 دولة، جالبين أفضل الأحذية حول العالم.",
    "about.values.community.title": "المجتمع أولاً",
    "about.values.community.description": "بني من قبل محبي الأحذية، لمحبي الأحذية. نحن نفهم ذلك.",
    "about.values.sustainable.title": "مستدام",
    "about.values.sustainable.description": "تغليف صديق للبيئة وخيارات شحن محايدة الكربون.",
    "about.journey": "رحلتنا",
    "about.timeline.2019.title": "البداية",
    "about.timeline.2019.description": "بدأ كمشروع شغف من قبل اثنين من عشاق الأحذية.",
    "about.timeline.2020.title": "الانتقال الرقمي",
    "about.timeline.2020.description": "أطلقنا منصتنا أثناء الجائحة.",
    "about.timeline.2021.title": "نمو سريع",
    "about.timeline.2021.description": "توسعنا إلى أكثر من 50 دولة و100 ألف عميل.",
    "about.timeline.2022.title": "مختبر التحقق",
    "about.timeline.2022.description": "افتتحنا منشأة التحقق من الأصالة المتطورة لدينا.",
    "about.timeline.2023.title": "حضور عالمي",
    "about.timeline.2023.description": "أصبحنا اسماً موثوقاً به في مجتمع الأحذية حول العالم.",
    "about.timeline.2024.title": "المستقبل",
    "about.timeline.2024.description": "نستمر في الابتكار وخدمة ثقافة الأحذية.",
    "about.cta.title": "انضم إلى الخزنة",
    "about.cta.description": "كن جزءاً من مجتمع يشاركك شغفك بالأحذية.",
    "about.cta.button": "تسوق الآن",

    // Contact
    "contact.info.email": "البريد الإلكتروني",
    "contact.info.phone": "الهاتف",
    "contact.info.address": "العنوان",
    "contact.title": "اتصل بنا",
    "contact.description": "لديك سؤال أو تحتاج مساعدة؟ نحن هنا لمساعدتك.",
    "contact.form-title": "أرسل لنا رسالة",
    "contact.name": "الاسم",
    "contact.name-placeholder": "اسمك",
    "contact.email": "البريد الإلكتروني",
    "contact.email-placeholder": "بريدك@الإلكتروني.com",
    "contact.subject": "الموضوع",
    "contact.select-topic": "اختر موضوعاً",
    "contact.topic.order": "استفسار الطلب",
    "contact.topic.product": "سؤال عن المنتج",
    "contact.topic.return": "الإرجاع والاستبدال",
    "contact.topic.other": "أخرى",
    "contact.message": "الرسالة",
    "contact.message-placeholder": "كيف يمكننا مساعدتك؟",
    "contact.send": "إرسال الرسالة",
    "contact.get-in-touch": "تواصل معنا",
    "contact.map-coming": "خريطة تفاعلية قريباً",
    "contact.live-chat": "ابدأ الدردشة الحية",
    "contact.message-sent": "تم إرسال الرسالة!",
    "contact.message-sent-desc": "سنعود إليك خلال 24 ساعة.",
    "contact.faq.track.question": "كيف أتتبع طلبي؟",
    "contact.faq.track.answer": "بمجرد شحن طلبك، ستتلقى رسالة بريد إلكتروني برقم التتبع. يمكنك أيضاً تتبع طلبك في حسابك تحت \"الطلبات\".",
    "contact.faq.return.question": "ما هي سياسة الإرجاع؟",
    "contact.faq.return.answer": "نقدم إرجاعاً مجانياً خلال 30 يوماً من الشراء للعناصر غير المستعملة في التغليف الأصلي. اتصل بنا لبدء الإرجاع.",
    "contact.faq.authentic.question": "هل جميع الأحذية أصلية؟",
    "contact.faq.authentic.answer": "نعم! كل حذاء يمر بعملية التحقق الصارمة لدينا. نضمن أصالة 100% أو استرد أموالك.",
    "contact.faq.shipping.question": "كم يستغرق الشحن؟",
    "contact.faq.shipping.answer": "الشحن القياسي يستغرق 5-7 أيام عمل. خيارات التوصيل السريع (2-3 أيام) والليلي متاحة عند الدفع.",
    "contact.faq.international.question": "هل تشحنون دولياً؟",
    "contact.faq.international.answer": "نعم! نشحن إلى أكثر من 100 دولة. الشحن الدولي يستغرق عادة 7-14 يوماً عمل.",
    "contact.faq.size.question": "كيف أعرف مقاسي؟",
    "contact.faq.size.answer": "تحقق من دليل المقاسات على كل صفحة منتج. إذا كنت بين مقاسين، نوصي بالاختيار الأكبر لملاءمة أكثر راحة.",
    "contact.faq.title": "الأسئلة الشائعة",

    // Wishlist
    "wishlist.title": "المفضلة",
    "wishlist.empty": "قائمة المفضلة فارغة",
    "wishlist.empty-desc": "احفظ المنتجات التي تعجبك بالنقر على أيقونة القلب.",
    "wishlist.browse": "تصفح المنتجات",
    "wishlist.share": "مشاركة",
    "wishlist.items-saved": "منتج محفوظ",
    "wishlist.move-to-cart": "نقل للسلة",
    "wishlist.moved-to-cart": "تم النقل للسلة",
    "wishlist.moved-desc": "تمت إضافته لسلتك",
    "wishlist.link-copied": "تم نسخ الرابط",
    "wishlist.link-copied-desc": "تم نسخ رابط المفضلة",
    "wishlist.copy-failed": "فشل نسخ الرابط",
    "wishlist.start-shopping": "ابدأ التسوق",

    // Search
    "search.title": "بحث",
    "search.placeholder": "ابحث عن أحذية رياضية...",
    "search.no-results": "لا توجد نتائج لـ",
    "search.popular": "عمليات بحث شائعة",

    // Account
    "account.title": "حسابي",
    "account.profile": "الملف الشخصي",
    "account.orders": "الطلبات",
    "account.addresses": "العناوين",
    "account.settings": "الإعدادات",
    "account.logout": "تسجيل الخروج",
    "account.login": "تسجيل الدخول",
    "account.register": "إنشاء حساب",
    "account.welcome": "مرحباً بعودتك",
    "account.profile-info": "معلومات الملف الشخصي",
    "account.first-name": "الاسم الأول",
    "account.last-name": "اسم العائلة",
    "account.save-changes": "حفظ التغييرات",
    "account.change-password": "تغيير كلمة المرور",
    "account.current-password": "كلمة المرور الحالية",
    "account.new-password": "كلمة المرور الجديدة",
    "account.confirm-password": "تأكيد كلمة المرور",
    "account.update-password": "تحديث كلمة المرور",
    "account.order-history": "سجل الطلبات",
    "account.items": "منتج",
    "account.saved-addresses": "العناوين المحفوظة",
    "account.add-address": "إضافة عنوان جديد",
    "account.default": "افتراضي",
    "account.edit": "تعديل",
    "account.wishlist-desc": "عرض وإدارة المنتجات المحفوظة.",
    "account.go-wishlist": "الذهاب للمفضلة",
    "account.preferences": "التفضيلات",
    "account.email-notifications": "إشعارات البريد",
    "account.email-notifications-desc": "تلقي تحديثات عن الطلبات والعروض",
    "account.sms-notifications": "إشعارات الرسائل",
    "account.sms-notifications-desc": "تحديثات نصية للشحن والتوصيل",
    "account.newsletter-pref": "النشرة الإخبارية",
    "account.newsletter-pref-desc": "تحديثات أسبوعية عن الإصدارات الجديدة",
    "account.preferred-size": "المقاس المفضل",
    "account.save-preferences": "حفظ التفضيلات",
    "account.work": "العمل",

    // Footer
    "footer.newsletter": "اشترك في النشرة الإخبارية",
    "footer.newsletter-desc": "احصل على آخر التحديثات حول الإصدارات الجديدة والعروض الحصرية.",
    "footer.subscribe": "اشترك",
    "footer.quick-links": "روابط سريعة",
    "footer.customer-service": "خدمة العملاء",
    "footer.follow-us": "تابعنا",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.faq": "الأسئلة الشائعة",
    "footer.returns": "الإرجاع",
    "footer.shop-title": "المتجر",
    "footer.help-title": "المساعدة",
    "footer.company-title": "الشركة",
    "footer.new-arrivals": "وصل حديثاً",
    "footer.best-sellers": "الأكثر مبيعاً",
    "footer.sale": "تخفيضات",
    "footer.all-products": "جميع المنتجات",
    "footer.contact-us": "اتصل بنا",
    "footer.faqs": "الأسئلة الشائعة",
    "footer.shipping": "الشحن",
    "footer.about-us": "من نحن",
    "footer.careers": "الوظائف",
    "footer.press": "الصحافة",
    "footer.sustainability": "الاستدامة",
    "footer.brand-desc": "وجهتك للأحذية الأصلية. نحن نقدم لك أحدث الإصدارات والكلاسيكيات الخالدة من أكثر العلامات التجارية المطلوبة في العالم.",
    "footer.copyright": "© 2024 SNKRVAULT. جميع الحقوق محفوظة.",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.overview": "نظرة عامة",
    "dashboard.products": "المنتجات",
    "dashboard.orders": "الطلبات",
    "dashboard.customers": "العملاء",
    "dashboard.analytics": "التحليلات",
    "dashboard.settings": "الإعدادات",
    "dashboard.total-revenue": "إجمالي الإيرادات",
    "dashboard.total-orders": "إجمالي الطلبات",
    "dashboard.total-customers": "إجمالي العملاء",
    "dashboard.total-products": "إجمالي المنتجات",
    "dashboard.recent-orders": "الطلبات الأخيرة",
    "dashboard.top-products": "أفضل المنتجات",
    "dashboard.revenue-chart": "الإيرادات الأسبوعية",
    "dashboard.orders-status": "الطلبات حسب الحالة",
    "dashboard.sales-by-category": "المبيعات حسب الفئة",
    "dashboard.add-product": "إضافة منتج",
    "dashboard.edit-product": "تعديل المنتج",
    "dashboard.delete-product": "حذف المنتج",
    "dashboard.search-products": "البحث في المنتجات...",
    "dashboard.search-orders": "البحث في الطلبات...",
    "dashboard.search-customers": "البحث في العملاء...",
    "dashboard.status": "الحالة",
    "dashboard.date": "التاريخ",
    "dashboard.customer": "العميل",
    "dashboard.amount": "المبلغ",
    "dashboard.action": "الإجراء",
    "dashboard.pending": "قيد الانتظار",
    "dashboard.processing": "قيد المعالجة",
    "dashboard.shipped": "تم الشحن",
    "dashboard.delivered": "تم التسليم",
    "dashboard.cancelled": "ملغي",
    "dashboard.view": "عرض",
    "dashboard.edit": "تعديل",
    "dashboard.delete": "حذف",
    "dashboard.save": "حفظ",
    "dashboard.cancel": "إلغاء",
    "dashboard.export": "تصدير",
    "dashboard.import": "استيراد",
    "dashboard.filter": "تصفية",
    "dashboard.all-time": "كل الوقت",
    "dashboard.today": "اليوم",
    "dashboard.this-week": "هذا الأسبوع",
    "dashboard.this-month": "هذا الشهر",
    "dashboard.this-year": "هذه السنة",
    "dashboard.from-last-month": "من الشهر الماضي",
    "dashboard.sold": "مبيعات",

    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.success": "تم بنجاح",
    "common.confirm": "تأكيد",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.add": "إضافة",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.view-all": "عرض الكل",
    "common.back": "رجوع",
    "common.continue": "متابعة",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.close": "إغلاق",
  },
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: "en",
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: "language-storage",
      storage: createJSONStorage(() => localStorage),
      skipHydration: true,
    }
  )
)

// Separate t() function — NOT inside the store
export function t(language: Language, key: string): string {
  return translations[language]?.[key] || key
}
