import { Product } from './store'

export const products: Product[] = [
  {
    id: 'snkr-001',
    name: 'Air Phantom X1',
    brand: 'Nike',
    category: 'Lifestyle',
    colorway: 'Triple Black / Volt',
    price: 180,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: false },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.7,
    reviewCount: 142,
    isNew: true,
    isLimited: false,
    tags: ['trending', 'featured'],
    description: 'Step into the future with the Air Phantom X1. Featuring revolutionary foam technology and a sleek silhouette.',
    details: ['Premium leather upper', 'React foam midsole', 'Rubber outsole', 'Reflective accents'],
    gender: 'Men',
  },
  {
    id: 'snkr-002',
    name: 'Ultra Boost 24',
    brand: 'Adidas',
    category: 'Running',
    colorway: 'Cloud White / Core Black',
    price: 190,
    salePrice: 149,
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
      'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: false },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: false },
    ],
    rating: 4.9,
    reviewCount: 328,
    isNew: false,
    isLimited: false,
    tags: ['bestseller', 'featured'],
    description: 'Experience unparalleled comfort with our most responsive Boost ever.',
    details: ['Primeknit+ upper', 'Boost midsole', 'Continental rubber outsole', 'Torsion system'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-003',
    name: 'Jordan 1 Retro High OG',
    brand: 'Jordan',
    category: 'Basketball',
    colorway: 'Chicago / Lost and Found',
    price: 180,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80',
      'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=800&q=80',
      'https://images.unsplash.com/photo-1585232004423-244e0e6904e3?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: false },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: false },
      { size: 'US 12', available: true },
    ],
    rating: 4.8,
    reviewCount: 567,
    isNew: false,
    isLimited: true,
    tags: ['grail', 'featured', 'trending'],
    description: 'The one that started it all. Remastered with premium materials.',
    details: ['Full-grain leather', 'Air-Sole unit', 'Rubber cupsole', 'Perforated toe box'],
    gender: 'Men',
  },
  {
    id: 'snkr-004',
    name: 'New Balance 550',
    brand: 'New Balance',
    category: 'Lifestyle',
    colorway: 'Sea Salt / Green',
    price: 130,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80',
      'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
    ],
    rating: 4.6,
    reviewCount: 234,
    isNew: true,
    isLimited: false,
    tags: ['trending'],
    description: 'Basketball-inspired heritage meets modern street style.',
    details: ['Leather and synthetic upper', 'EVA midsole', 'Rubber outsole', 'Padded collar'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-005',
    name: 'Puma RS-X',
    brand: 'Puma',
    category: 'Lifestyle',
    colorway: 'Black / Red / Yellow',
    price: 110,
    salePrice: 89,
    images: [
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.3,
    reviewCount: 89,
    isNew: false,
    isLimited: false,
    tags: ['sale'],
    description: 'Extreme reinvention with bold design and chunky silhouette.',
    details: ['Mesh and leather upper', 'RS foam midsole', 'Rubber outsole', 'TPU heel clip'],
    gender: 'Men',
  },
  {
    id: 'snkr-006',
    name: 'Air Max 97',
    brand: 'Nike',
    category: 'Lifestyle',
    colorway: 'Silver Bullet',
    price: 175,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1514989940723-e8e51d675571?w=800&q=80',
      'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80',
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: false },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: false },
    ],
    rating: 4.7,
    reviewCount: 445,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'trending'],
    description: 'The revolutionary full-length Air Max unit that changed everything.',
    details: ['Synthetic upper', 'Full-length Air Max', 'Rubber Waffle outsole', '3M reflective'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-007',
    name: 'Yeezy 350 V2',
    brand: 'Adidas',
    category: 'Lifestyle',
    colorway: 'Bone / Bone',
    price: 230,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365778-7875a359c0be?w=800&q=80',
      'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: false },
      { size: 'US 8', available: false },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: false },
      { size: 'US 12', available: false },
    ],
    rating: 4.5,
    reviewCount: 892,
    isNew: false,
    isLimited: true,
    tags: ['grail', 'limited'],
    description: 'Iconic silhouette with Primeknit upper and Boost cushioning.',
    details: ['Primeknit upper', 'Boost midsole', 'Rubber outsole', 'Pull tab'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-008',
    name: 'Dunk Low',
    brand: 'Nike',
    category: 'Lifestyle',
    colorway: 'Panda',
    price: 110,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1612015670817-0127d21628d4?w=800&q=80',
      'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80',
      'https://images.unsplash.com/photo-1579338908476-3a3a1d71a706?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
    ],
    rating: 4.8,
    reviewCount: 1204,
    isNew: false,
    isLimited: false,
    tags: ['bestseller', 'trending', 'featured'],
    description: 'The classic B-ball icon gets street ready with leather luxury.',
    details: ['Leather upper', 'Foam midsole', 'Rubber outsole', 'Padded collar'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-009',
    name: 'Forum Low',
    brand: 'Adidas',
    category: 'Lifestyle',
    colorway: 'White / Royal Blue',
    price: 100,
    salePrice: 79,
    images: [
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.4,
    reviewCount: 167,
    isNew: false,
    isLimited: false,
    tags: ['sale', 'classic'],
    description: '80s basketball legend returns with signature X-strap.',
    details: ['Leather upper', 'EVA midsole', 'Rubber cupsole', 'Iconic ankle strap'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-010',
    name: 'Air Force 1 07',
    brand: 'Nike',
    category: 'Lifestyle',
    colorway: 'Triple White',
    price: 115,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&q=80',
      'https://images.unsplash.com/photo-1595461137351-5050694be048?w=800&q=80',
      'https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.9,
    reviewCount: 2341,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'bestseller', 'featured'],
    description: 'The legend lives on. Premium leather construction with Air cushioning.',
    details: ['Full-grain leather', 'Air-Sole unit', 'Non-marking outsole', 'Perforated toe'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-011',
    name: 'Fresh Foam 1080v12',
    brand: 'New Balance',
    category: 'Running',
    colorway: 'Black / Magnet',
    price: 165,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.6,
    reviewCount: 312,
    isNew: true,
    isLimited: false,
    tags: ['new', 'running'],
    description: 'Our most cushioned Fresh Foam experience with Hypoknit upper.',
    details: ['Hypoknit upper', 'Fresh Foam X midsole', 'Blown rubber outsole', 'Ultra Heel'],
    gender: 'Men',
  },
  {
    id: 'snkr-012',
    name: 'Gel-Kayano 29',
    brand: 'Asics',
    category: 'Running',
    colorway: 'Piedmont Grey / Black',
    price: 160,
    salePrice: 129,
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
      'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: false },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.7,
    reviewCount: 456,
    isNew: false,
    isLimited: false,
    tags: ['sale', 'running'],
    description: 'Premium stability running shoe with FF BLAST+ cushioning.',
    details: ['Engineered mesh upper', 'FF BLAST+ midsole', 'AHAR+ outsole', '4D Guidance System'],
    gender: 'Men',
  },
  {
    id: 'snkr-013',
    name: 'Classic Leather',
    brand: 'Reebok',
    category: 'Lifestyle',
    colorway: 'Chalk / Glen Green',
    price: 80,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.3,
    reviewCount: 234,
    isNew: false,
    isLimited: false,
    tags: ['classic'],
    description: 'Timeless design. Soft leather upper with die-cut EVA midsole.',
    details: ['Soft leather upper', 'Die-cut EVA midsole', 'High-abrasion rubber outsole', 'Padded foam sockliner'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-014',
    name: 'Suede Classic XXI',
    brand: 'Puma',
    category: 'Lifestyle',
    colorway: 'Peacoat / White',
    price: 75,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80',
      'https://images.unsplash.com/photo-1514989940723-e8e51d675571?w=800&q=80',
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
    ],
    rating: 4.5,
    reviewCount: 567,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'trending'],
    description: 'The iconic streetwear staple since 1968.',
    details: ['Suede upper', 'Rubber midsole', 'Rubber outsole', 'Formstrip branding'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-015',
    name: 'Chuck 70 High',
    brand: 'Converse',
    category: 'Lifestyle',
    colorway: 'Black / Egret',
    price: 90,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800&q=80',
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.8,
    reviewCount: 1089,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'bestseller'],
    description: 'Premium materials and vintage details define the Chuck 70.',
    details: ['Canvas upper', 'OrthoLite insole', 'Rubber midsole', 'Higher foxing'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-016',
    name: 'Air Jordan 4 Retro',
    brand: 'Jordan',
    category: 'Basketball',
    colorway: 'Military Black',
    price: 210,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=800&q=80',
      'https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800&q=80',
      'https://images.unsplash.com/photo-1585232004423-244e0e6904e3?w=800&q=80',
    ],
    sizes: [
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: false },
      { size: 'US 11', available: true },
      { size: 'US 12', available: false },
    ],
    rating: 4.9,
    reviewCount: 723,
    isNew: true,
    isLimited: true,
    tags: ['grail', 'limited', 'new'],
    description: 'The iconic Flight-inspired design returns in premium form.',
    details: ['Leather and textile upper', 'Visible Air unit', 'Rubber outsole', 'Plastic wing eyelets'],
    gender: 'Men',
  },
  {
    id: 'snkr-017',
    name: 'Blazer Mid 77',
    brand: 'Nike',
    category: 'Lifestyle',
    colorway: 'White / Black',
    price: 105,
    salePrice: 85,
    images: [
      'https://images.unsplash.com/photo-1579338908476-3a3a1d71a706?w=800&q=80',
      'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&q=80',
      'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
    ],
    rating: 4.6,
    reviewCount: 445,
    isNew: false,
    isLimited: false,
    tags: ['sale', 'classic'],
    description: 'Vintage hoops style with a worn-in look from day one.',
    details: ['Leather upper', 'Foam midsole', 'Rubber outsole', 'Exposed foam tongue'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-018',
    name: 'Gazelle',
    brand: 'Adidas',
    category: 'Lifestyle',
    colorway: 'Collegiate Navy / White',
    price: 100,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
      'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
    ],
    rating: 4.7,
    reviewCount: 678,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'trending'],
    description: 'The iconic 90s indoor shoe updated for the streets.',
    details: ['Suede upper', 'Rubber cupsole', 'Synthetic lining', 'Signature 3-Stripes'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-019',
    name: 'Vaporfly 3',
    brand: 'Nike',
    category: 'Running',
    colorway: 'Volt / Black',
    price: 260,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    ],
    sizes: [
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: false },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: false },
    ],
    rating: 4.9,
    reviewCount: 234,
    isNew: true,
    isLimited: false,
    tags: ['new', 'performance', 'running'],
    description: 'Race day ready with ZoomX foam and carbon fiber plate.',
    details: ['Atomknit 3.0 upper', 'ZoomX foam', 'Full-length carbon plate', 'Rubber outsole pods'],
    gender: 'Unisex',
  },
  {
    id: 'snkr-020',
    name: 'Old Skool',
    brand: 'Vans',
    category: 'Lifestyle',
    colorway: 'Black / White',
    price: 70,
    salePrice: null,
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80',
      'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800&q=80',
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80',
    ],
    sizes: [
      { size: 'US 6', available: true },
      { size: 'US 7', available: true },
      { size: 'US 8', available: true },
      { size: 'US 9', available: true },
      { size: 'US 10', available: true },
      { size: 'US 11', available: true },
      { size: 'US 12', available: true },
    ],
    rating: 4.7,
    reviewCount: 1567,
    isNew: false,
    isLimited: false,
    tags: ['classic', 'bestseller'],
    description: 'The first shoe to feature the iconic Vans Sidestripe.',
    details: ['Canvas and suede upper', 'Padded collar', 'Vulcanized outsole', 'Waffle tread'],
    gender: 'Unisex',
  },
]

export const brands = ['Nike', 'Adidas', 'Jordan', 'New Balance', 'Puma', 'Asics', 'Reebok', 'Converse', 'Vans']
export const categories = ['Lifestyle', 'Running', 'Basketball', 'Training']
export const genders = ['Men', 'Women', 'Unisex', 'Kids']
export const sizes = ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12']
